export const KEYS = {
  CONFIRM_ADD_GROUP: 'CONFIRM_ADD_GROUP',
  WRITE_MESSAGE: 'WRITE_MESSAGE',
  WRITE_MESSAGE_CANCEL: 'WRITE_MESSAGE_CANCEL',
  KEYWORDS_INPUT: 'KEYWORDS_INPUT',
  STICKER_EDIT: 'STICKER_EDIT',
  PAPER_DETAIL: 'PAPER_DETAIL',
} as const;
