declare module '*.svg';
declare module '*.glb';
declare module '*.woff';
declare module '*.jpg';
declare module '*.json';
declare module '*.jpeg';
declare module '*.png';
declare module '*.webp';
declare module '*.gif';
